### ISSUE TITLE
Error during activating language server

### ISSUE THREAD

**Issue by Andrea055** [jasonlyu123/SvelteVisualStudio#60]
Hi!, I can't use this extension in my computer, when I try to open a Svelte file, Visual studio give me this error: Task Failed - Activating language client Svelte For Visual Studio: Language server failed to initialize during the SendingInitializeRequest Stage.

Any fix?
Thanks

**Comment by jasonlyu123** [comment]
Are you using visual studio 2019 or 2022?

I did see an error with 2022 in 1.11.0 but I am not sure what happened because I can't reproduce it with a development instance and newly built installer. Guess it's a build problem. I just released 1.12.0. Can you try it again?

**Comment by Andrea055** [comment]
I'm using VS2022, with new build all works. Thank you
